# Generated by Django 5.1.2 on 2024-10-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_biens', '0003_bien_est_publié_bien_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='date_debut_disponibilite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='date_fin_disponibilite',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
