# Generated by Django 5.1.2 on 2024-10-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_biens', '0004_bien_date_debut_disponibilite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='commentaire',
            field=models.TextField(help_text='Votre avis sur ce bien (max 1000 caractères).', max_length=1000, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note (1-5)'),
        ),
    ]
