# Generated by Django 5.1.2 on 2024-10-14 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_biens', '0006_avis_nom_utilisateur_bien_nom_bien_prix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='avis',
            options={'ordering': ['-date_creation'], 'verbose_name_plural': 'Avis'},
        ),
        migrations.AlterField(
            model_name='avis',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_biens.bien'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='commentaire',
            field=models.TextField(help_text='Votre avis sur ce bien (max 1000 caractères).', max_length=1000, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
