# Generated by Django 5.1.2 on 2024-10-14 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_biens', '0007_review_alter_avis_options_alter_avis_bien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='location_biens.bien'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
